apps/accounts/urls.py
# apps/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.profile_view, name='profile'),
	path("company/", views.catalog_edit_view,name="catalog_edit"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static
from django.http import HttpResponse
from django.views.decorators.http import require_GET
from django.template.loader import render_to_string
from django.contrib import sitemaps
from django.contrib.sitemaps.views import sitemap
from .sitemaps import StaticViewSitemap, AboutSitemap, PartnerSitemap


@require_GET
def robots_txt(request):
    text = render_to_string("core/robots.txt")
    return HttpResponse(text, content_type="text/plain")


sitemaps = {
    'static': StaticViewSitemap,
    'about': AboutSitemap,
    'partners': PartnerSitemap,
}


urlpatterns = [
    path("robots.txt", robots_txt),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
     path('ckeditor/', include('ckeditor_uploader.urls')),
    path('i18n/', include('django.conf.urls.i18n')),  # для смены языка через POST
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
	path('accounts/', include('allauth.urls')),
     
    path('', include(('apps.core.urls', 'core'), namespace='core')),  # namespace
	path('profile/', include(('apps.accounts.urls', 'accounts'), namespace='accounts')),
    path('about/', include(('apps.about.urls', 'about'), namespace='about')),
     path('news/', include(('apps.news.urls', 'news'), namespace='news')),
    
)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/accounts/models.py
# apps/accounts/models.py
from django.db import models
import os
from .validators import validate_file_size
from datetime import datetime
from django.utils.html import format_html
from django.utils.text import slugify
from django.contrib.auth.models import User
from django_countries.fields import CountryField
import uuid

def user_file_path(instance, filename, folder):
    # определяем пользователя через профиль
    user = getattr(instance, "user", None) or getattr(instance, "profile", None) and instance.profile.user
    if user:
        name_slug = slugify(f"{user.first_name}_{user.last_name}") or user.username
    else:
        name_slug = "unknown_user"

    base, ext = os.path.splitext(filename)
    unique = uuid.uuid4().hex[:8]
    new_filename = f"{base}_{unique}{ext}"
    return os.path.join(name_slug, folder, new_filename)




def photo_path(instance, filename):
    return user_file_path(instance, filename, 'photo')

def passport_copy_path(instance, filename):
    return user_file_path(instance, filename, 'passport_copy')

def employment_verification_path(instance, filename):
    return user_file_path(instance, filename, 'employment_verification')

def diploma_scan_path(instance, filename):
    return user_file_path(instance, filename, 'diploma_scan')

def logo_path(instance, filename):
    return user_file_path(instance, filename, 'logo')

class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile", verbose_name="Пользователь", help_text="Связанный аккаунт пользователя")
    
	DEGREE_CHOICES = [
		('bachelor', "Bachelor's"),
		('master', "Master's"),
		('phd', "PhD"),
		('other', "Other"),
	]
    # Персональные данные
	first_name = models.CharField(max_length=100, verbose_name="Имя", help_text="Введите ваше имя")  
	last_name = models.CharField(max_length=100, verbose_name="Фамилия", help_text="Введите вашу фамилию")   
	father_name = models.CharField(max_length=50, blank=True, null=True, verbose_name="Отчество", help_text="Введите отчество (необязательно)")  
	company = models.CharField(max_length=255, blank=True, null=True, verbose_name="Компания", help_text="Название вашей компании")
	position = models.CharField(max_length=255, blank=True, null=True, verbose_name="Должность", help_text="Ваша должность в компании")  
	birth_date = models.DateField(blank=True, null=True, verbose_name="Дата рождения", help_text="Формат: ГГГГ-ММ-ДД")
	country = CountryField(blank=True, null=True, verbose_name="Страна", help_text="Выберите вашу страну")
	address = models.TextField(blank=True, null=True, verbose_name="Адрес", help_text="Полный адрес проживания")
	passport_number = models.CharField(max_length=50, blank=True, null=True, verbose_name="Номер паспорта", help_text="Номер вашего паспорта")
	passport_issue_date = models.DateField(blank=True, null=True, verbose_name="Дата выдачи паспорта", help_text="Формат: ГГГГ-ММ-ДД")
	passport_expiry_date = models.DateField(blank=True, null=True, verbose_name="Дата окончания паспорта", help_text="Формат: ГГГГ-ММ-ДД")
	education_degree = models.CharField(max_length=100, blank=True, null=True, choices=DEGREE_CHOICES, verbose_name="Степень образования", help_text="Например: Bachelor's, Master's")
	education_institute = models.CharField(max_length=255, blank=True, null=True, verbose_name="Учебное заведение", help_text="Название университета или колледжа")
	specialization = models.CharField(max_length=255, blank=True, null=True, verbose_name="Специализация", help_text="Ваша специализация или факультет")
	website = models.URLField(blank=True, null=True, verbose_name="Веб-сайт", help_text="Если есть личный сайт или компания")

	# Файлы
	photo = models.ImageField(upload_to=photo_path, blank=True, null=True, verbose_name="Фото", help_text="Загрузите ваше фото", validators=[validate_file_size],)
	passport_copy = models.FileField(upload_to=passport_copy_path, blank=True, null=True, verbose_name="Копия паспорта", help_text="Загрузите скан вашего паспорта", validators=[validate_file_size],)
	employment_verification = models.FileField(upload_to=employment_verification_path, blank=True, null=True, verbose_name="Справка с работы", help_text="Загрузите подтверждение занятости", validators=[validate_file_size],)
	diploma_scan = models.FileField(upload_to=diploma_scan_path,blank=True, null=True, verbose_name="Скан диплома", help_text="Загрузите скан вашего диплома", validators=[validate_file_size],)
     
	 #info
	has_paid_delegate_fee = models.BooleanField( default=False, verbose_name="Оплатил делегатский взнос")
	visa_processed = models.BooleanField( default=False, verbose_name="Подача на визу обработана")
	# ===== VISA =====
	need_visa = models.BooleanField(
		default=False,
		verbose_name="Needs visa",
		help_text="Does the user require a visa"
	)

	def __str__(self):
		return f"{self.user.username} Profile"



class CatalogEntry(models.Model):
	profile = models.OneToOneField(
        Profile,
        on_delete=models.CASCADE,
        related_name="catalog",
        verbose_name="Профиль"
    )
	description = models.TextField(verbose_name="О компании", help_text="Введите инфомрацию о вашей компании", blank=True, null=True)
	img = models.ImageField(upload_to=logo_path, verbose_name="Изображение", help_text="Загрузите логотип вашей компании", blank=True, null=True)
	created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания", help_text="Дата и время создания записи", )
	updated_at = models.DateTimeField(auto_now=True, verbose_name="Дата обновления", help_text="Дата и время последнего обновления записи", )
       

	def __str__(self):
		return f'Catalog Entry {self.id}'

apps/accounts/forms.py
from allauth.account.forms import LoginForm, SignupForm, ResetPasswordForm, ResetPasswordKeyForm
from django import forms
from django.utils.translation import gettext_lazy as _
from django_countries.widgets import CountrySelectWidget

from .models import Profile, CatalogEntry


class CustomLoginForm(LoginForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # поле login (email)
        self.fields["login"].label = _("Email")
        self.fields["login"].widget.attrs.update({
            "class": "auth__input",
            "placeholder": " ",
            "autocomplete": "email",
        })

        # поле password
        self.fields["password"].label = _("Password")
        self.fields["password"].widget.attrs.update({
            "class": "auth__input",
            "placeholder": " ",
            "autocomplete": "current-password",
        })
        
		# поле remember (чекбокс)
        if "remember" in self.fields:
            self.fields["remember"].widget.attrs.update({
                "class": "auth__check",  # отдельный класс для чекбокса
            })



class CustomSignupForm(SignupForm):
    agree_terms = forms.BooleanField(
        required=True,
        label=_("I have read and agree to the Privacy Policy and Terms of Service"),
        widget=forms.CheckboxInput(attrs={
            "class": "auth__check",
        })
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["email"].label = _("Email")
        self.fields["email"].widget.attrs.update({
            "class": "auth__input",
            "placeholder": " ",
            "autocomplete": "email",
        })

        self.fields["password1"].label = _("Password")
        self.fields["password1"].widget.attrs.update({
            "class": "auth__input",
            "placeholder": " ",
            "autocomplete": "new-password",
        })

        self.fields["password2"].label = _("Confirm Password")
        self.fields["password2"].widget.attrs.update({
            "class": "auth__input",
            "placeholder": " ",
            "autocomplete": "new-password",
        })
        

class CustomPasswordResetForm(ResetPasswordForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.update({
            "class": "auth__input",
            "placeholder": " ",
            "autocomplete": "email",
        })
        self.fields['email'].label = _("Email")
        

class CustomPasswordResetFromKeyForm(ResetPasswordKeyForm):
    """
    Форма для установки нового пароля по ссылке из письма.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Новые пароли
        self.fields['password1'].label = _("New Password")
        self.fields['password1'].widget.attrs.update({
            "class": "auth__input",
            "placeholder": " ",
            "autocomplete": "new-password",
        })

        self.fields['password2'].label = _("Confirm Password")
        self.fields['password2'].widget.attrs.update({
            "class": "auth__input",
            "placeholder": " ",
            "autocomplete": "new-password",
        })
        

# profile


# apps/accounts/forms.py

class ProfileForm(forms.ModelForm):
	need_visa = forms.BooleanField(
		required=False,
		label=_("Visa "),
		widget=forms.CheckboxInput(attrs={
			"class": "profile__input",
			"id": "id_need_visa"
		})
	)

	class Meta:
		model = Profile
		exclude = ['user', 'has_paid_delegate_fee', 'visa_processed']
		widgets = {
			'first_name': forms.TextInput(attrs={'class': 'profile__input'}),
			'last_name': forms.TextInput(attrs={'class': 'profile__input'}),
			'father_name': forms.TextInput(attrs={'class': 'profile__input'}),
			'birth_date': forms.DateInput(attrs={'type': 'date', 'class': 'profile__input'}, format='%Y-%m-%d'),
			'company': forms.TextInput(attrs={'class': 'profile__input'}),
			'position': forms.TextInput(attrs={'class': 'profile__input'}),
			'country': CountrySelectWidget(attrs={'class': 'profile__input'}),
			'address': forms.TextInput(attrs={'class': 'profile__input'}),
			'passport_number': forms.TextInput(attrs={'class': 'profile__input'}),
			'passport_issue_date': forms.DateInput(attrs={'type': 'date', 'class': 'profile__input'}),
			'passport_expiry_date': forms.DateInput(attrs={'type': 'date', 'class': 'profile__input'}),
			'education_degree': forms.Select(attrs={'class': 'profile__input'}),
			'education_institute': forms.TextInput(attrs={'class': 'profile__input'}),
			'specialization': forms.TextInput(attrs={'class': 'profile__input'}),
			'website': forms.URLInput(attrs={'class': 'profile__input'}),
			'photo': forms.FileInput(attrs={'class': 'profile__input'}),
			'passport_copy': forms.FileInput(attrs={'class': 'profile__input'}),
			'employment_verification': forms.FileInput(attrs={'class': 'profile__input'}),
			'diploma_scan': forms.FileInput(attrs={'class': 'profile__input'}),
		}
		help_texts = {
			'passport_copy': 'Max file size: 5 MB',
			'diploma_scan': 'Max file size: 5 MB',
		}

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)

		# 🔹 Переводимые лейблы
		self.fields['first_name'].label = _("First name")
		self.fields['last_name'].label = _("Last name")
		self.fields['father_name'].label = _("Father name")
		self.fields['birth_date'].label = _("Date of birth")
		self.fields['company'].label = _("Company")
		self.fields['position'].label = _("Position")
		self.fields['country'].label = _("Country")
		self.fields['address'].label = _("Address")
		self.fields['passport_number'].label = _("Passport number")
		self.fields['passport_issue_date'].label = _("Passport issue date")
		self.fields['passport_expiry_date'].label = _("Passport expiry date")
		self.fields['education_degree'].label = _("Education level")
		self.fields['education_institute'].label = _("Educational institution")
		self.fields['specialization'].label = _("Specialization")
		self.fields['website'].label = _("Website")
		self.fields['photo'].label = _("Profile photo")
		self.fields['passport_copy'].label = _("Passport photo")
		self.fields['employment_verification'].label = _("Employment verification photo")
		self.fields['diploma_scan'].label = _("Diploma photo")

		# 🔹 Формат дат при редактировании
		for date_field in ['birth_date', 'passport_issue_date', 'passport_expiry_date']:
			if self.instance and getattr(self.instance, date_field):
				self.initial[date_field] = getattr(self.instance, date_field).strftime('%Y-%m-%d')

		# 🔹 Переводимые choices
		country_choices = list(self.fields['country'].choices)
		if country_choices and country_choices[0][0] == '':
			country_choices.pop(0)
		self.fields['country'].choices = [('', _("Select country"))] + country_choices

		edu_choices = list(self.fields['education_degree'].choices)
		if edu_choices and edu_choices[0][0] == '':
			edu_choices.pop(0)
		self.fields['education_degree'].choices = [('', _("Select level"))] + edu_choices
        



class CatalogEntryForm(forms.ModelForm):
    class Meta:
        model = CatalogEntry
        exclude = ["profile"]
        widgets = {
            "description": forms.Textarea(attrs={"class": "profile__input", "rows": 5}),
            "img": forms.FileInput(attrs={"class": "profile__input", "accept": "image/*"}),
        }

apps/accounts/views.py
# apps/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
import pdfkit
import os
from django.http import HttpResponse
from django.template.loader import render_to_string
from django.shortcuts import get_object_or_404

from .forms import ProfileForm, CatalogEntryForm
from .models import Profile, CatalogEntry

@login_required
def profile_view(request):
    profile, created = Profile.objects.get_or_create(user=request.user)

    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user  # обязательно привязать user
            profile.save()  # теперь instance.user есть, upload_to сработает правильно
            form.save_m2m()
            return redirect('accounts:profile')
    else:
        form = ProfileForm(instance=profile)

    return render(request, 'accounts/profile.html', {'form': form})





@login_required
def catalog_edit_view(request):
    profile = request.user.profile

    catalog, _ = CatalogEntry.objects.get_or_create(profile=profile)

    if request.method == "POST":
        form = CatalogEntryForm(request.POST, request.FILES, instance=catalog)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.profile = profile  # обязательно привязываем профиль
            obj.save()
            return redirect("accounts:catalog_edit")
    else:
        form = CatalogEntryForm(instance=catalog)

    return render(request, "accounts/catalog.html", {"form": form})

apps/accounts/templates/accounts/catalog.html
{% extends "core/base.html" %}
{% load static i18n %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'accounts/css/profile.css' %}">
{% endblock extra_css %}

{% block content %}
<section class="profile">
    <div class="container">
        <div class="profile__wrapper">

            <form method="post" enctype="multipart/form-data" class="profile__form">
                {% csrf_token %}

                <!-- ===== TOP (IMAGE) ===== -->
                <div class="profile__top">
                    <div class="profile__img">
                        <img
                            src="{% if form.instance.img %}{{ form.instance.img.url }}{% else %}{% static 'accounts/img/profile_default.png' %}{% endif %}"
                            alt="company logo"
                            class="profile__img-preview"
                            id="imgPreview"
                        >

                        <label class="profile__img-overlay">
                            {{ form.img }}
                            <span class="profile__img-text">
                                {% if form.instance.img %}
                                    {% trans "Change logo" %}
                                {% else %}
                                    {% trans "Upload logo" %}
                                {% endif %}
                            </span>
                        </label>
                    </div>
                </div>

                <!-- ===== CONTENT ===== -->
                <h3 class="profile__title">{% trans "Company Information" %}</h3>

                <div class="profile__bottom">

                    <!-- Description -->
                    <div class="profile__field fl-label">
                        {{ form.description }}
                        <label for="{{ form.description.id_for_label }}">
                            {{ form.description.label }}
                        </label>

                        {% if form.description.errors %}
                            <div class="profile__error">
                                {% for error in form.description.errors %}
                                    {{ error }}
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>

                </div>

                <button type="submit" class="button profile__btn">
                    {% trans "Save" %}
                </button>
				<a href='{% url "accounts:profile" %}' type="submit" class="button profile__back-btn">
                    {% trans "Back" %}
                </a>

            </form>

        </div>
    </div>
</section>

<!-- ===== IMAGE PREVIEW SCRIPT ===== -->
<script>
    const input = document.getElementById("id_img");
    const preview = document.getElementById("imgPreview");

    if (input) {
        input.addEventListener("change", function () {
            const file = this.files[0];
            if (file) {
                preview.src = URL.createObjectURL(file);
            }
        });
    }
</script>

{% endblock %}

apps/accounts/templates/accounts/profile.html
{% extends "core/base.html" %}
{% load i18n static %}
{% load custom_filters %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'accounts/css/visa_checkbox.css' %}">
<link rel="stylesheet" href="{% static 'accounts/css/profile.css' %}">
{% endblock extra_css %}

{% block content %}
<section class="profile">
    <div class="container">
        <div class="profile__wrapper">

            <form method="post" enctype="multipart/form-data" class="profile__form">
                {% csrf_token %}

                <!-- ===== TOP ===== -->
                <div class="profile__top">
                    <div class="profile__img">
						<img
							src="{% if user.profile.photo %}{{ user.profile.photo.url }}{% else %}{% static 'accounts/img/profile_default.png' %}{% endif %}"
							alt="profile image"
							class="profile__img-preview"
							id="photoPreview"
						>

						<label class="profile__img-overlay">
							<input type="file" name="photo" id="id_photo" accept="image/*">
							<span class="profile__img-text">
								{% if user.profile.photo %}{% trans "Change photo" %} {% else %}{% trans "Upload photo" %} {% endif %}
							</span>
						</label>
					</div>
					<div class="profile__help">{% trans "The photo must be 3x4." %}</div>
                    <div class="profile__basic">
                        <div class="profile__row">
                            <div class="profile__field-top fl-label">
                                {{ form.first_name }}
                                <label for="{{ form.first_name.id_for_label }}">
                                    {{ form.first_name.label }}
                                </label>
                                {{ form.first_name.errors }}
                            </div>

                            <div class="profile__field-top fl-label">
                                {{ form.last_name }}
                                <label for="{{ form.last_name.id_for_label }}">
                                    {{ form.last_name.label }}
                                </label>
                                {{ form.last_name.errors }}
                            </div>
                        </div>

                        <div class="profile__row">
                            <div class="profile__field-top fl-label">
                                {{ form.father_name }}
                                <label for="{{ form.father_name.id_for_label }}">
                                    {{ form.father_name.label }}
                                </label>
                                {{ form.father_name.errors }}
                            </div>

                            <div class="profile__field-top fl-label">
                                {{ form.birth_date }}
                                <label for="{{ form.birth_date.id_for_label }}">
                                    {{ form.birth_date.label }}
                                </label>
                                {{ form.birth_date.errors }}
                            </div>
                        </div>
                    </div>
                </div>
				<h3 class="profile__title">{% trans "Your Details" %}</h3>

				<div class="profile__visa-toggle">
					<span class="profile__visa-title">
						{% trans "Do you need a visa?" %}
					</span>
					<div class="checkbox-wrapper-55">
						<label class="rocker rocker-small">
							{{ form.need_visa }}
							 {% comment %} <label for="{{ form.need_visa.id_for_label }}">
								{{ form.need_visa.label }}
							</label> {% endcomment %}
							<span class="switch-left">{% trans "Yes" %}</span>
							<span class="switch-right">{% trans "No" %}</span>
						</label>
					</div>
				</div>

              	<!-- ===== BOTTOM ===== -->
				<div class="profile__bottom">
					
					{% for field in form %}
						{% if field.name not in "first_name last_name father_name birth_date photo  need_visa" %}
							<div class="profile__field fl-label">

								<!-- input и label сразу -->
								{{ field }}
								<label for="{{ field.id_for_label }}">
									{{ field.label }}
								</label>

								<!-- Файлы: Файл сохранён, если есть -->
								{% if field.name in "passport_copy employment_verification photo diploma_scan" %}
									{% with file_obj=user.profile|attr:field.name %}
										{% if file_obj %}
											<div class="profile__file-saved">
												{% trans "File is saved:" %} <a href="{{ file_obj.url }}" target="_blank">{{ file_obj.name|cut:"media/" }}</a>
											</div>
										{% endif %}
									{% endwith %}
								{% endif %}


								<!-- Ошибки -->
								{% comment %} {% if field.errors %}
									<div class="profile__error">
										{% for error in field.errors %}
											{{ error }}
										{% endfor %}
									</div>
								{% endif %} {% endcomment %}

							</div>
						{% endif %}
					{% endfor %}

				</div>



                <button type="submit" class="button profile__btn profile__btn_save">
                    {% trans "Save Changes" %}
                </button>

            </form>
			<a href="{% url 'accounts:catalog_edit' %}" class="button profile__btn">{% trans "Company information" %}  </a>
			<div class="profile__btns">
				<form method="post" action="{% url 'account_logout' %}">
					{% csrf_token %}
					<button type="submit" class="button profile__logout-btn">
						{% trans "Log out" %}
					</button>
				</form>

				<a href="{% url 'account_reset_password' %}" class="button profile__reset-btn">{% trans "Reset Password" %} </a>

			</div>

        </div>
    </div>
</section>

<div id="fileErrorPopup" class="file-popup">
    <div class="file-popup__content">
        <span id="fileErrorText">{% trans 'File is too large. Maximum size is 15 MB.' %}</span>
        <button type="button" class="file-popup__close">&times;</button>
    </div>
</div>


{% endblock %}



{% block extra_js %}
<script src="{% static 'accounts/js/profile.js' %}"></script>
{% endblock extra_js %}