apps/about/urls.py
from django.urls import path, include
from . import views

app_name = 'about'

urlpatterns = [
	path('', views.about_view, name='about'),
]

apps/accounts/urls.py
# apps/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.profile_view, name='profile'),
	path("company/", views.catalog_edit_view,name="catalog_edit"),
]

apps/core/urls.py
from django.urls import path
from . import views


app_name = "core"

urlpatterns = [
    path('', views.index, name='index'),
	path('privacy-policy/', views.privacy_policy, name='privacy_policy'),
    path('terms-of-service/', views.terms_of_service, name='terms_of_service'),
]

apps/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
	path('', views.news, name='news'),
	path('<slug:slug>/', views.newsDetail, name='detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static
from django.http import HttpResponse
from django.views.decorators.http import require_GET
from django.template.loader import render_to_string
from django.contrib import sitemaps
from django.contrib.sitemaps.views import sitemap
from .sitemaps import StaticViewSitemap, AboutSitemap, PartnerSitemap


@require_GET
def robots_txt(request):
    text = render_to_string("core/robots.txt")
    return HttpResponse(text, content_type="text/plain")


sitemaps = {
    'static': StaticViewSitemap,
    'about': AboutSitemap,
    'partners': PartnerSitemap,
}


urlpatterns = [
    path("robots.txt", robots_txt),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap'),
     path('ckeditor/', include('ckeditor_uploader.urls')),
    path('i18n/', include('django.conf.urls.i18n')),  # для смены языка через POST
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
	path('accounts/', include('allauth.urls')),
     
    path('', include(('apps.core.urls', 'core'), namespace='core')),  # namespace
	path('profile/', include(('apps.accounts.urls', 'accounts'), namespace='accounts')),
    path('about/', include(('apps.about.urls', 'about'), namespace='about')),
     path('news/', include(('apps.news.urls', 'news'), namespace='news')),
    
)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/core/models.py
from django.db import models
from parler.models import TranslatableModel, TranslatedFields
from ckeditor.fields import RichTextField
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill
from django.urls import reverse

class Intro(models.Model):
	video = models.FileField(upload_to='intro_videos/%Y/%m/%d', verbose_name='Intro Video')


class About(TranslatableModel):
	translations = TranslatedFields(
		title=models.CharField(max_length=200, verbose_name='Title', blank=True, null=True),
		description=RichTextField(verbose_name='Description', blank=True, null=True),
	)
	image = models.ImageField(upload_to='about_images/%Y/%m/%d', verbose_name='About Image')

	def get_absolute_url(self):
		return reverse('core:index')


class Tabs(models.Model):
	img = models.ImageField(upload_to='tabs_images/%Y/%m/%d', verbose_name='Tab Image')
	# Оптимизированная версия
	img_optimized = ImageSpecField(
		source='img',
		processors=[
			ResizeToFill(800, 800),  
		],
		format='WEBP',
    	options={'quality': 75}
	)

	def __str__(self):
		return f"Tab {self.id}" or " "


class PartnershipType(TranslatableModel):
	translations = TranslatedFields(
		name=models.CharField(max_length=100, verbose_name='Partnership Type Name')
	)


	def __str__(self):
		return self.name or " "
	

    

class PartnerLevel(TranslatableModel):
	translations = TranslatedFields(
		name=models.CharField(max_length=50, verbose_name='Partner Level Name')
	)
	slug = models.SlugField(
		max_length=50,
		unique=True,
		help_text='Используется для CSS классов (gold, silver, bronze)'
	)
	priority = models.PositiveIntegerField(default=0)

	def __str__(self):
		return self.name or ' '



class Partner(TranslatableModel):
	translations = TranslatedFields(
		name=models.CharField(max_length=255, verbose_name='Partner Name', blank=True, null=True),	
	)
	logo = models.ImageField(upload_to='partners/logo/%Y/%m/%d')
	partnership_type = models.ForeignKey(
		PartnershipType,
		on_delete=models.CASCADE,
		related_name='partners'
	)

	level = models.ForeignKey(
		PartnerLevel,
		on_delete=models.SET_NULL,
		null=True,
		blank=True,
		related_name='partners'
	)
	link = models.URLField(verbose_name='ссылка', blank=True, null=True)

	def get_absolute_url(self):
		return reverse('core:index')


	def __str__(self):
		return self.safe_translation_getter('name', any_language=True) or ''

apps/core/views.py
from django.shortcuts import render
from .models import Intro, About, Tabs, PartnershipType
from apps.news.models import News

def index(request):
	intro = Intro.objects.first()
	about = About.objects.first()
	tabs = Tabs.objects.all()[:3]
	partnership_types = PartnershipType.objects.prefetch_related('partners__level').all()
     
	latest_news = News.objects.all()[:4]
	more_news = News.objects.all().exclude(id__in=[n.id for n in latest_news])[:5]

	context = {
		'intro': intro,
        'about': about,
        'tabs': tabs,
		'partnership_types': partnership_types,
        'latest_news' : latest_news,
        'more_news' : more_news
	}

	return render(request, 'core/index.html', context)


def privacy_policy(request):
    return render(request, 'core/docs/privacy_policy.html')

def terms_of_service(request):
    return render(request, 'core/docs/terms_of_service.html')

apps/core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="{{ request.LANGUAGE_CODE }}">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Title -->
    <title>{% block title %}IFT2026 — Investment to the Future of Turkmenistan{% endblock %}</title>

    <meta name="description" content="{% block meta_description %}{% endblock %}">
    <meta name="keywords" content="investment forum, Turkmenistan, IFT2026, business, economy">

    <!-- Open Graph -->
    <meta property="og:title" content="{% block og_title %}IFT2026{% endblock %}">
    <meta property="og:description" content="{% block og_description %}{% endblock %}">
    <meta property="og:type" content="website">
    <meta property="og:url" content="{{ request.build_absolute_uri }}">
    <meta property="og:image" content="{% block og_image %}{% static 'img/og_image.png' %}{% endblock %}">


    <!-- Favicon -->
    <!-- Классический favicon -->
	<link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicons/favicon-32x32.png' %}">
	<link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicons/favicon-16x16.png' %}">
	<link rel="shortcut icon" href="{% static 'img/favicons/favicon.ico' %}">

	<!-- Apple touch icon -->
	<link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/favicons/apple-touch-icon.png' %}">

	<!-- Android / PWA -->
	<link rel="manifest" href="{% static 'img/favicons/site.webmanifest' %}">
	<meta name="theme-color" content="#ffffff"> <!-- цвет панели браузера на мобильных -->


    <!-- Глобальные стили -->
	<link rel="stylesheet" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" href="{% static 'css/container.css' %}">
    <link rel="stylesheet" href="{% static 'css/variables.css' %}">
	<link rel="stylesheet" href="{% static 'css/lineicons.css' %}">
	<link rel="stylesheet" href="{% static 'core/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/global.css' %}">

    <!-- Дополнительные стили для конкретной страницы -->
    {% block extra_css %}{% endblock %}
</head>

<body>

    {% include 'core/components/header.html' %}

    <main class="main">
        {% block content %}{% endblock %}
    </main>

    {% include 'core/components/footer.html' %}


    <!-- Глобальный JS -->
    <script type="module" src="{% static 'js/global.js' %}"></script>

    <!-- Дополнительные JS для конкретной страницы -->
    {% block extra_js %}{% endblock %}
</body>

</html>

apps/core/templates/core/index.html
{% extends "core/base.html" %}
{% load static i18n %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/swiper-bundle.min.css' %}" />
<link rel="stylesheet" href="{% static 'core/css/index.css' %}">
<link rel="stylesheet" href="{% static 'core/css/partners.css' %}">
{% endblock extra_css %}

{% block meta_description %}
	{% trans "IFT2026 — Investment to the Future of Turkmenistan. International investment forum uniting investors, business and government." %} 
{% endblock %}

{% block meta_keywords %}
 	{% trans "investment forum, Turkmenistan investment, IFT2026, business forum, economy" %} 
{% endblock %}

{% block og_title %}
	{% trans "IFT2026 — Investment Forum" %} 
{% endblock %}

{% block og_description %}
{% endblock %}


{% block content %}
<section class="intro">
	<video class="intro__video" autoplay muted loop playsinline >
    <source src="{{ intro.video.url }}" type="video/mp4">
</video>

	<div class="container">
		<h1 class="intro__title">{% trans "IFT2026 Investment in the future of Turkmenistan" %} </h1>
		<p class="intro__subtitle">{% trans "Join discussions, share ideas, and connect with delegates from around the world." %} </p>
		<div class="intro__buttons">
			<a href="" class="intro__button button">{% trans "Official support" %}</a>
			<a href="" class="intro__button button">{% trans "Agenda" %} </a>
			<a href="#partners" class="intro__button button">{% trans "Partners" %} </a>
		</div>
	</div>
</section>

<section class="about">
	<div class="container">
		<div class="about__wrapper">
			<div class="about__img"><img src="{{ about.image.url }}" alt="ift 2026"></div>
			<div class="about__content">
				<h3 class="about__title title">{{ about.title }}</h3>
				<div class="about__descr">{{ about.description|safe }}</div>
				<a href="{% url "about:about" %}" class="button about__btn">{% trans "Details" %} </a>
			</div>
			<div class="about__tabs">
				{% for tab in tabs %}
				<div class="about__tab">
					<img src="{{ tab.img_optimized.url }}" alt="Tab Image">
				</div>
				{% endfor %}
			</div>
		</div>
	</div>
</section>


<section class="news">
	<div class="container">
		<div class="news__top">
			<div class="news__title title">{% trans "Latest News" %}</div>
			<div class="news__btn">
				<a href="{% url "news:news" %}" class="button">{% trans "More News & Insights" %}</a>
			</div>
			
		</div>
		
		<div class="news__wrapper">
			<div class="news__left">
				{% if latest_news %}
					{% for news in latest_news %}
						<div class="news__item">
							<a href="{% url 'news:detail' slug=news.slug %}" class="news__img">
								<img 
									src="{% if news.image %}{{ news.image_preview.url }}{% else %}{% static 'img/noPhoto.jpg' %}{% endif %}" 
									alt="{{ news.title }}" 
									loading="lazy">
							</a>
							<div class="news__name">
								<div class="news__date">{{ news.date }}</div>
								<a href="{% url 'news:detail' slug=news.slug %}">{{ news.title }}</a>
							</div>
							{% comment %} <div class="news__descr">
								{{ news.content|truncatewords:30|safe }}
							</div> {% endcomment %}
						</div>
					{% endfor %}
				{% else %}
					<p>{% trans "No news available at the moment." %}</p>
				{% endif %}
			</div>
			<div class="news__right">
				{% if more_news %}
					{% with news=more_news.0 %}
						<div class="news__img">
							<a href="{% url 'news:detail' slug=news.slug %}">
								<img 
									src="{% if news.image %}{{ news.image_preview.url }}{% else %}{% static 'img/noPhoto.jpg' %}{% endif %}" 
									alt="{{ news.title }}" 
									loading="lazy">
							</a>
						</div>
						<div class="news__name">
							<div class="news__date">{{ news.date|date:"d.m.Y" }}</div>
							<a href="{% url 'news:detail' slug=news.slug %}">{{ news.title }}</a>
						</div>
					{% endwith %}
				{% else %}
					<p>{% trans "No news available." %}</p>
				{% endif %}
			</div>

			
		</div>
	</div>
</section>

<section class="partners" id="partners">
	<div class="container">
		<div class="partners__wrapper">
			{% comment %} <h4 class="title partners__title">{% trans "Partners" %} </h4> {% endcomment %}
			<div class="partners__top">
				<ul class="partners__menu">
					{% for type in partnership_types %}
						<li class="partners__item {% if forloop.first %}active{% endif %}" 
							data-type="{{ type.id }}">
							<span>{{ type.name }}</span>
						</li>
					{% endfor %}
				</ul>
			</div>

			<div class="partners__bottom swiper">
				<div class="partners__list swiper-wrapper">
					{% for partner in partnership_types.0.partners.all %}
						<a class="partners__list-item swiper-slide" href="{{ partner.link }}" target="_blank">
							
							<img 
								src="{{ partner.logo.url }}" 
								alt="{{ partner.name }}" 
								class="partners__img
									{% if partner.level %}
										partners__img--{{ partner.level.name|lower }}
									{% endif %}"
							>

							<div class="partners__name">{{ partner.name }}</div>

						</a>
					{% endfor %}
				</div>

				<div class="swiper-button-prev"></div>
				<div class="swiper-button-next"></div>
			</div>

		</div>
	</div>
</section>


{% comment %} <section class="speakers">
	<div class="container">
		<div class="speakers__wrapper">
			<div class="speakers__item">
				<div class="speakers__img"><img src="" alt=""></div>
				<div class="speakers__name"></div>
				<div class="speakers__position"></div>
			</div>
		</div>
	</div>
</section> {% endcomment %}


{% if user.is_authenticated %}
<div id="profile-popup" class="popup-overlay">
	<div class="popup-content">
		<button id="close-popup" class="popup-close">&times;</button>
		<h2>Заполните профиль</h2>
		<p>Чтобы учавствовать в форуме, пожалуйста, заполните информацию о себе.</p>
		<a href="{% url 'accounts:profile' %}" class="button">Перейти к профилю</a>
	</div>
</div>
{% endif %}



{% endblock content %}

{% block extra_js %}
<script src="{% static 'js/swiper-bundle.min.js' %}"></script>
<script src="{% static 'core/js/popup.js' %}"></script>
<script src="{% static 'core/js/index.js' %}"></script>




<script>
document.addEventListener('DOMContentLoaded', function () {

    const menuItems = document.querySelectorAll('.partners__item');
    const sliderEl = document.querySelector('.partners__bottom'); // ❗ КОНТЕЙНЕР
    const wrapperEl = sliderEl.querySelector('.partners__list');

    const allPartners = [
        {% for type in partnership_types %}
        {
            typeId: {{ type.id }},
            partners: [
                {% for partner in type.partners.all %}
                {
                    name: "{{ partner.name|escapejs }}",
                    logo: "{{ partner.logo.url|default:'' }}"
                },
                {% endfor %}
            ]
        },
        {% endfor %}
    ];

    // === ИНИЦИАЛИЗАЦИЯ SWIPER ===
    const swiper = new Swiper(sliderEl, {
        slidesPerView: 5,
        spaceBetween: 20,

        navigation: {
            nextEl: '.swiper-button-next',
            prevEl: '.swiper-button-prev',
        },

        breakpoints: {
            1200: { slidesPerView: 5 },
            992:  { slidesPerView: 4 },
            768:  { slidesPerView: 3 },
            480:  { slidesPerView: 2 },
			320: { slidesPerView: 1 },
        },

        watchOverflow: true,
        observer: true,
        observeParents: true,
    });

    // === ТАБЫ ===
    menuItems.forEach(item => {
        item.addEventListener('click', () => {
            menuItems.forEach(i => i.classList.remove('active'));
            item.classList.add('active');

            const typeId = item.dataset.type;
            const typePartners = allPartners.find(t => t.typeId == typeId)?.partners || [];

            // очистка
            swiper.removeAllSlides();

            // новые слайды
            swiper.appendSlide(
                typePartners.map(p => `
                    <div class="swiper-slide partners__list-item">
                        <img src="${p.logo}" alt="${p.name}" class="partners__img">
                        <div class="partners__name">${p.name}</div>
                    </div>
                `)
            );

            swiper.slideTo(0);
            swiper.update();
        });
    });

});
</script>



{% endblock extra_js %}